args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("--file=", args, value = TRUE)
if (length(file_arg) > 0) { root <- normalizePath(file.path(dirname(normalizePath(sub("--file=", "", file_arg))), ".."), mustWork = TRUE) } else { root <- normalizePath(".", mustWork = TRUE) }
data_dir <- file.path(root, "data"); outputs_dir <- file.path(root, "outputs"); dir.create(outputs_dir, showWarnings = FALSE, recursive = TRUE)
technologies <- read.csv(file.path(data_dir, "technology_profiles.csv"))
controls <- read.csv(file.path(data_dir, "governance_controls.csv"))
risks <- read.csv(file.path(data_dir, "distributional_risks.csv"))
technologies$enabling_score <- round(0.16*technologies$maturity + 0.18*technologies$capability_growth + 0.16*technologies$institutional_support + 0.16*technologies$infrastructure_readiness + 0.14*technologies$governance_readiness + 0.12*technologies$social_legitimacy + 0.08*(1-technologies$ecological_pressure), 4)
technologies$risk_score <- round(0.25*technologies$distributional_risk + 0.20*technologies$ecological_pressure + 0.20*(1-technologies$governance_readiness) + 0.15*(1-technologies$social_legitimacy) + 0.20*technologies$strategic_importance, 4)
technologies$foresight_priority_score <- round(0.55*technologies$risk_score + 0.45*technologies$enabling_score, 4)
technologies <- technologies[order(-technologies$foresight_priority_score), ]
controls$governance_readiness_score <- round(0.22*controls$regulatory_capacity + 0.20*controls$standards_maturity + 0.22*controls$accountability_infrastructure + 0.18*controls$public_participation + 0.18*controls$enforcement_feasibility, 4)
controls$governance_gap_score <- round(1 - controls$governance_readiness_score, 4)
risks$distributional_risk_score <- round(0.25*risks$burden_concentration + 0.22*risks$exposure + 0.22*risks$worker_displacement + 0.21*risks$community_vulnerability + 0.10*(1-risks$mitigation_capacity), 4)
write.csv(technologies, file.path(outputs_dir, "r_technology_foresight_profiles.csv"), row.names = FALSE)
write.csv(controls, file.path(outputs_dir, "r_governance_readiness_scores.csv"), row.names = FALSE)
write.csv(risks, file.path(outputs_dir, "r_distributional_risk_scores.csv"), row.names = FALSE)
print(technologies[, c("technology_id", "technology_name", "foresight_priority_score")])
cat("R workflow complete. Outputs written to:", outputs_dir, "\n")
