DROP VIEW IF EXISTS workflow_integrity_scores;
DROP VIEW IF EXISTS lineage_dependency_scores;
DROP VIEW IF EXISTS strategy_evaluation_scores;
DROP VIEW IF EXISTS assumption_fragility_scores;
DROP VIEW IF EXISTS scenario_traceability_scores;
DROP VIEW IF EXISTS signal_data_quality_scores;
DROP VIEW IF EXISTS driver_data_quality_scores;
DROP TABLE IF EXISTS workflow_runs;
DROP TABLE IF EXISTS lineage_edges;
DROP TABLE IF EXISTS strategy_evaluations;
DROP TABLE IF EXISTS assumptions;
DROP TABLE IF EXISTS scenarios;
DROP TABLE IF EXISTS signals;
DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS validation_rules;
CREATE TABLE drivers (driver_id TEXT PRIMARY KEY, driver_name TEXT NOT NULL, domain TEXT, impact REAL, uncertainty REAL, source_traceability REAL, freshness REAL, completeness REAL, validity REAL, review_status TEXT, source_note TEXT);
CREATE TABLE signals (signal_id TEXT PRIMARY KEY, driver_id TEXT, signal_name TEXT NOT NULL, signal_type TEXT, novelty REAL, relevance REAL, urgency REAL, evidence_quality REAL, affected_voice REAL, source_traceability REAL, collection_date TEXT, interpretation TEXT, FOREIGN KEY(driver_id) REFERENCES drivers(driver_id));
CREATE TABLE scenarios (scenario_id TEXT PRIMARY KEY, scenario_name TEXT NOT NULL, scenario_family TEXT, version TEXT, time_horizon TEXT, linked_drivers TEXT, assumption_count INTEGER, evidence_note_count INTEGER, review_status TEXT, narrative_summary TEXT);
CREATE TABLE assumptions (assumption_id TEXT PRIMARY KEY, scenario_id TEXT, assumption_name TEXT, assumption_text TEXT, confidence REAL, fragility REAL, strategic_impact REAL, linked_indicator TEXT, revision_rule TEXT, FOREIGN KEY(scenario_id) REFERENCES scenarios(scenario_id));
CREATE TABLE strategy_evaluations (evaluation_id TEXT PRIMARY KEY, scenario_id TEXT, strategy_id TEXT, strategy_name TEXT, effectiveness REAL, feasibility REAL, equity REAL, legitimacy REAL, adaptability REAL, reviewer TEXT, review_date TEXT, notes TEXT, FOREIGN KEY(scenario_id) REFERENCES scenarios(scenario_id));
CREATE TABLE lineage_edges (edge_id TEXT PRIMARY KEY, source_object_id TEXT, source_object_type TEXT, target_object_id TEXT, target_object_type TEXT, relationship_type TEXT, dependency_strength REAL, description TEXT);
CREATE TABLE workflow_runs (run_id TEXT PRIMARY KEY, workflow_name TEXT, input_version TEXT, script_name TEXT, expected_outputs INTEGER, generated_outputs INTEGER, status TEXT, run_date TEXT, notes TEXT);
CREATE TABLE validation_rules (rule_id TEXT PRIMARY KEY, object_type TEXT, field_name TEXT, rule_type TEXT, rule_description TEXT, severity TEXT);
CREATE VIEW driver_data_quality_scores AS SELECT driver_id, driver_name, domain, ROUND(0.25*completeness + 0.25*validity + 0.25*freshness + 0.25*source_traceability, 4) AS data_quality_score, ROUND(impact*uncertainty, 4) AS driver_priority_score, review_status FROM drivers;
CREATE VIEW signal_data_quality_scores AS SELECT signal_id, driver_id, signal_name, signal_type, ROUND(0.25*evidence_quality + 0.25*source_traceability + 0.20*relevance + 0.15*urgency + 0.15*affected_voice, 4) AS data_quality_score, ROUND(0.16*novelty + 0.24*relevance + 0.22*urgency + 0.18*evidence_quality + 0.10*affected_voice + 0.10*source_traceability, 4) AS warning_priority_score FROM signals;
CREATE VIEW scenario_traceability_scores AS SELECT scenario_id, scenario_name, scenario_family, version, assumption_count, evidence_note_count, review_status, ROUND(0.35*MIN(((LENGTH(linked_drivers)-LENGTH(REPLACE(linked_drivers,';',''))+1)/5.0),1.0) + 0.30*MIN((assumption_count/6.0),1.0) + 0.25*MIN((evidence_note_count/10.0),1.0) + 0.10*CASE WHEN review_status='reviewed' THEN 1.0 ELSE 0.65 END, 4) AS scenario_traceability_score FROM scenarios;
CREATE VIEW assumption_fragility_scores AS SELECT assumption_id, scenario_id, assumption_name, ROUND(0.35*(1-confidence) + 0.35*fragility + 0.30*strategic_impact, 4) AS assumption_fragility_score, linked_indicator, revision_rule FROM assumptions;
CREATE VIEW strategy_evaluation_scores AS SELECT evaluation_id, scenario_id, strategy_id, strategy_name, ROUND(0.25*effectiveness + 0.20*feasibility + 0.20*equity + 0.20*legitimacy + 0.15*adaptability, 4) AS strategy_viability_score, reviewer, review_date FROM strategy_evaluations;
CREATE VIEW lineage_dependency_scores AS SELECT edge_id, source_object_id, source_object_type, target_object_id, target_object_type, relationship_type, ROUND(dependency_strength, 4) AS lineage_criticality_score, description FROM lineage_edges;
CREATE VIEW workflow_integrity_scores AS SELECT run_id, workflow_name, input_version, script_name, expected_outputs, generated_outputs, status, ROUND(MIN((generated_outputs * 1.0 / CASE WHEN expected_outputs <= 0 THEN 1 ELSE expected_outputs END), 1.0), 4) AS workflow_integrity_score, run_date FROM workflow_runs;
