DROP VIEW IF EXISTS strategy_option_scores;
DROP VIEW IF EXISTS distributional_risk_scores;
DROP VIEW IF EXISTS governance_readiness_scores;
DROP VIEW IF EXISTS signal_priority_scores;
DROP VIEW IF EXISTS technology_foresight_profiles;
DROP TABLE IF EXISTS strategy_options;
DROP TABLE IF EXISTS pathway_parameters;
DROP TABLE IF EXISTS distributional_risks;
DROP TABLE IF EXISTS governance_controls;
DROP TABLE IF EXISTS scenario_conditions;
DROP TABLE IF EXISTS technology_signals;
DROP TABLE IF EXISTS technology_profiles;
CREATE TABLE technology_profiles (technology_id TEXT PRIMARY KEY, technology_name TEXT NOT NULL, technology_domain TEXT, maturity REAL, capability_growth REAL, institutional_support REAL, infrastructure_readiness REAL, governance_readiness REAL, social_legitimacy REAL, ecological_pressure REAL, distributional_risk REAL, strategic_importance REAL, description TEXT);
CREATE TABLE technology_signals (signal_id TEXT PRIMARY KEY, technology_id TEXT, signal_name TEXT, signal_type TEXT, novelty REAL, relevance REAL, urgency REAL, evidence_quality REAL, affected_voice REAL, governance_relevance REAL, interpretation TEXT);
CREATE TABLE scenario_conditions (scenario_id TEXT PRIMARY KEY, scenario_name TEXT, scenario_family TEXT, regulation_strength REAL, public_trust REAL, capital_availability REAL, infrastructure_capacity REAL, geopolitical_stability REAL, ecological_constraint REAL, labor_protection REAL, description TEXT);
CREATE TABLE governance_controls (control_id TEXT PRIMARY KEY, technology_id TEXT, control_name TEXT, control_type TEXT, regulatory_capacity REAL, standards_maturity REAL, accountability_infrastructure REAL, public_participation REAL, enforcement_feasibility REAL, description TEXT);
CREATE TABLE distributional_risks (risk_id TEXT PRIMARY KEY, technology_id TEXT, risk_name TEXT, burden_concentration REAL, exposure REAL, worker_displacement REAL, community_vulnerability REAL, mitigation_capacity REAL, description TEXT);
CREATE TABLE pathway_parameters (pathway_id TEXT PRIMARY KEY, technology_id TEXT, pathway_name TEXT, capability REAL, institutional_support REAL, governance_readiness REAL, public_legitimacy REAL, constraint_pressure REAL, distributional_risk REAL, initial_state REAL, time_horizon INTEGER);
CREATE TABLE strategy_options (strategy_id TEXT PRIMARY KEY, strategy_name TEXT, strategy_type TEXT, technology_scope TEXT, acceleration REAL, precaution REAL, public_investment REAL, governance_strength REAL, labor_protection REAL, ecological_safeguard REAL, description TEXT);
CREATE VIEW technology_foresight_profiles AS SELECT technology_id, technology_name, technology_domain, ROUND(0.16*maturity+0.18*capability_growth+0.16*institutional_support+0.16*infrastructure_readiness+0.14*governance_readiness+0.12*social_legitimacy+0.08*(1-ecological_pressure),4) AS enabling_score, ROUND(0.25*distributional_risk+0.20*ecological_pressure+0.20*(1-governance_readiness)+0.15*(1-social_legitimacy)+0.20*strategic_importance,4) AS risk_score FROM technology_profiles;
CREATE VIEW signal_priority_scores AS SELECT signal_id, technology_id, signal_name, signal_type, ROUND(0.14*novelty+0.24*relevance+0.20*urgency+0.14*evidence_quality+0.12*affected_voice+0.16*governance_relevance,4) AS signal_priority_score, interpretation FROM technology_signals;
CREATE VIEW governance_readiness_scores AS SELECT control_id, technology_id, control_name, control_type, ROUND(0.22*regulatory_capacity+0.20*standards_maturity+0.22*accountability_infrastructure+0.18*public_participation+0.18*enforcement_feasibility,4) AS governance_readiness_score, ROUND(1-(0.22*regulatory_capacity+0.20*standards_maturity+0.22*accountability_infrastructure+0.18*public_participation+0.18*enforcement_feasibility),4) AS governance_gap_score FROM governance_controls;
CREATE VIEW distributional_risk_scores AS SELECT risk_id, technology_id, risk_name, ROUND(0.25*burden_concentration+0.22*exposure+0.22*worker_displacement+0.21*community_vulnerability+0.10*(1-mitigation_capacity),4) AS distributional_risk_score, mitigation_capacity FROM distributional_risks;
CREATE VIEW strategy_option_scores AS SELECT strategy_id, strategy_name, strategy_type, technology_scope, ROUND(0.16*acceleration+0.18*precaution+0.18*public_investment+0.20*governance_strength+0.16*labor_protection+0.12*ecological_safeguard,4) AS strategy_viability_score, ROUND(0.12*acceleration+0.20*precaution+0.20*public_investment+0.22*governance_strength+0.16*labor_protection+0.10*ecological_safeguard,4) AS public_interest_score FROM strategy_options;
